src/MP/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from posts import views

urlpatterns = [
    url(r'^', include("posts.urls")),
    url(r'^admin/', admin.site.urls),
    #Open posts Dynamic
    #url(r'^posts/', include("posts.urls")),
    #Open posts
    #url(r'^posts/$', views.post_home),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .import views

app_name = 'posts'

urlpatterns = [
	url(r'^$', views.post_home, name= 'main'),
	url(r'^home/', views.post_home, name= 'home'),
    url(r'^contacts/', views.post_contact, name= 'contact'),
    url(r'^case/', views.post_case, name= 'case'),
    url(r'^ddr3/', views.post_ddr3, name= 'ddr3'),
    url(r'^ddr4/', views.post_ddr4, name= 'ddr4'),
    url(r'^gpu/', views.post_gpu, name= 'gpu'),
    url(r'^moth1150/', views.post_moth1150, name= 'moth1150'),
    url(r'^moth1151/', views.post_moth1151, name= 'moth1151'),
    url(r'^proc1150/', views.post_proc1150, name= 'proc1150'),
    url(r'^proc1151/', views.post_proc1151, name= 'proc1151'),
    url(r'^psu/', views.post_psu, name= 'psu'),
    url(r'^ssd/', views.post_store, name= 'store'),
]

src/templates/ddr3.html
{%load staticfiles%}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PC BUILDER</title>

    <!-- Bootstrap Core CSS -->
    <link href='{% static "css/bootstrap.min.css"%}' rel="stylesheet">

    <!-- Custom CSS -->
    <link href='{% static "css/sb-admin.css"%}' rel="stylesheet">

    <!-- Custom Fonts -->
    <link href='{% static "font-awesome/css/font-awesome.min.css"%}' rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href='{% url "posts:main" %}'>PC BUILDER</a>
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li class="active">
                        <a href='{% url "posts:home" %}'><i class="fa fa-fw fa-wrench"></i> BUILD PC</a>
                    </li>
                    <li>
                        <a><i class="fa fa-fw fa-desktop"></i> COMPONENTS</a>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo_p"><i class="glyphicon glyphicon-triangle-right"></i> Intel Processor <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo_p" class="collapse">
                            <li>
                                <a href='{% url "posts:proc1150" %}'>LGA 1150</a>
                            </li>
                            <li>
                                <a href='{% url "posts:proc1151" %}'>LGA 1151</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo_mb"><i class="glyphicon glyphicon-triangle-right"></i> Intel Motherboard <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo_mb" class="collapse">
                            <li>
                                <a href='{% url "posts:moth1150" %}'>LGA 1150</a>
                            </li>
                            <li>
                                <a href='{% url "posts:moth1151" %}'>LGA 1151</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo_me"><i class="glyphicon glyphicon-triangle-right"></i> Memory <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo_me" class="collapse">
                            <li>
                                <a href='{% url "posts:ddr4" %}'>DDR4</a>
                            </li>
                            <li>
                                <a href='{% url "posts:ddr3" %}'>DDR3</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href='{% url "posts:store" %}'><i class="glyphicon glyphicon-triangle-right"></i> Storage </a>
                    </li>
                    <li>
                        <a href='{% url "posts:gpu" %}'><i class="glyphicon glyphicon-triangle-right"></i>Graphics Card</a>
                    </li>
                    <li>
                        <a href='{% url "posts:psu" %}'><i class="glyphicon glyphicon-triangle-right"></i>Power Supply</a>
                    </li>
                    <li>
                        <a href='{% url "posts:case" %}'><i class="glyphicon glyphicon-triangle-right"></i>Casing</a>
                    </li>
                    <li>
                        <a href='{% url "posts:contact" %}'><i class="glyphicon glyphicon-earphone"></i>CONTACT US</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            DDR3 Memory Module
                        </h1>
                    </div>
                    {% for obj in items %}

                    <div class="row">
                        <div class="col-lg-12">
                            <div class="thumbnail">
                                {% if obj.mem_image %}
                                    <img src='{{ obj.mem_image.url }}' class='img-responsive'>
                                {% endif %}
                                <div class="caption">
                                    <h3>{{ obj.mem_model }}</h3>
                                    <p>{{ obj.mem_content|linebreaks }}</p>
                                <fieldset disabled>
                                    <button type="" class="btn btn-primary">P {{ obj.mem_cost }}</button>
                                </fieldset>
                                </div>
                            </div>
                        </div>
                    </div>

                {% endfor %}
                </div>
                <!-- /.row -->

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src='{% static "js/jquery.js"%}'></script>

    <!-- Bootstrap Core JavaScript -->
    <script src='{% static "js/bootstrap.min.js"%}'></script>

</body>

</html>

src/templates/ddr4.html
{%load staticfiles%}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PC BUILDER</title>

    <!-- Bootstrap Core CSS -->
    <link href='{% static "css/bootstrap.min.css"%}' rel="stylesheet">

    <!-- Custom CSS -->
    <link href='{% static "css/sb-admin.css"%}' rel="stylesheet">

    <!-- Custom Fonts -->
    <link href='{% static "font-awesome/css/font-awesome.min.css"%}' rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href='{% url "posts:main" %}'>PC BUILDER</a>
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li class="active">
                        <a href='{% url "posts:home" %}'><i class="fa fa-fw fa-wrench"></i> BUILD PC</a>
                    </li>
                    <li>
                        <a><i class="fa fa-fw fa-desktop"></i> COMPONENTS</a>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo_p"><i class="glyphicon glyphicon-triangle-right"></i> Intel Processor <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo_p" class="collapse">
                            <li>
                                <a href='{% url "posts:proc1150" %}'>LGA 1150</a>
                            </li>
                            <li>
                                <a href='{% url "posts:proc1151" %}'>LGA 1151</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo_mb"><i class="glyphicon glyphicon-triangle-right"></i> Intel Motherboard <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo_mb" class="collapse">
                            <li>
                                <a href='{% url "posts:moth1150" %}'>LGA 1150</a>
                            </li>
                            <li>
                                <a href='{% url "posts:moth1151" %}'>LGA 1151</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo_me"><i class="glyphicon glyphicon-triangle-right"></i> Memory <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo_me" class="collapse">
                            <li>
                                <a href='{% url "posts:ddr4" %}'>DDR4</a>
                            </li>
                            <li>
                                <a href='{% url "posts:ddr3" %}'>DDR3</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href='{% url "posts:store" %}'><i class="glyphicon glyphicon-triangle-right"></i> Storage </a>
                    </li>
                    <li>
                        <a href='{% url "posts:gpu" %}'><i class="glyphicon glyphicon-triangle-right"></i>Graphics Card</a>
                    </li>
                    <li>
                        <a href='{% url "posts:psu" %}'><i class="glyphicon glyphicon-triangle-right"></i>Power Supply</a>
                    </li>
                    <li>
                        <a href='{% url "posts:case" %}'><i class="glyphicon glyphicon-triangle-right"></i>Casing</a>
                    </li>
                    <li>
                        <a href='{% url "posts:contact" %}'><i class="glyphicon glyphicon-earphone"></i>CONTACT US</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            DDR4 Memory Module
                        </h1>
                    </div>
                    {% for obj in items %}

                    <div class="row">
                        <div class="col-lg-12">
                            <div class="thumbnail">
                                {% if obj.mem_image %}
                                    <img src='{{ obj.mem_image.url }}' class='img-responsive'>
                                {% endif %}
                                <div class="caption">
                                    <h3>{{ obj.mem_model }}</h3>
                                    <p>{{ obj.mem_content|linebreaks }}</p>
                                <fieldset disabled>
                                    <button type="" class="btn btn-primary">P {{ obj.mem_cost }}</button>
                                </fieldset>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% endfor %}
                </div>
                <!-- /.row -->

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src='{% static "js/jquery.js"%}'></script>

    <!-- Bootstrap Core JavaScript -->
    <script src='{% static "js/bootstrap.min.js"%}'></script>

</body>

</html>

src/templates/gpu.html
{%load staticfiles%}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PC BUILDER</title>

    <!-- Bootstrap Core CSS -->
    <link href='{% static "css/bootstrap.min.css"%}' rel="stylesheet">

    <!-- Custom CSS -->
    <link href='{% static "css/sb-admin.css"%}' rel="stylesheet">

    <!-- Custom Fonts -->
    <link href='{% static "font-awesome/css/font-awesome.min.css"%}' rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href='{% url "posts:main" %}'>PC BUILDER</a>
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li class="active">
                        <a href='{% url "posts:home" %}'><i class="fa fa-fw fa-wrench"></i> BUILD PC</a>
                    </li>
                    <li>
                        <a><i class="fa fa-fw fa-desktop"></i> COMPONENTS</a>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo_p"><i class="glyphicon glyphicon-triangle-right"></i> Intel Processor <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo_p" class="collapse">
                            <li>
                                <a href='{% url "posts:proc1150" %}'>LGA 1150</a>
                            </li>
                            <li>
                                <a href='{% url "posts:proc1151" %}'>LGA 1151</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo_mb"><i class="glyphicon glyphicon-triangle-right"></i> Intel Motherboard <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo_mb" class="collapse">
                            <li>
                                <a href='{% url "posts:moth1150" %}'>LGA 1150</a>
                            </li>
                            <li>
                                <a href='{% url "posts:moth1151" %}'>LGA 1151</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo_me"><i class="glyphicon glyphicon-triangle-right"></i> Memory <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo_me" class="collapse">
                            <li>
                                <a href='{% url "posts:ddr4" %}'>DDR4</a>
                            </li>
                            <li>
                                <a href='{% url "posts:ddr3" %}'>DDR3</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href='{% url "posts:store" %}'><i class="glyphicon glyphicon-triangle-right"></i> Storage </a>
                    </li>
                    <li>
                        <a href='{% url "posts:gpu" %}'><i class="glyphicon glyphicon-triangle-right"></i>Graphics Card</a>
                    </li>
                    <li>
                        <a href='{% url "posts:psu" %}'><i class="glyphicon glyphicon-triangle-right"></i>Power Supply</a>
                    </li>
                    <li>
                        <a href='{% url "posts:case" %}'><i class="glyphicon glyphicon-triangle-right"></i>Casing</a>
                    </li>
                    <li>
                        <a href='{% url "posts:contact" %}'><i class="glyphicon glyphicon-earphone"></i>CONTACT US</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Graphics Card
                        </h1>
                    </div>
                    {% for obj in items %}

                    <div class="row">
                        <div class="col-lg-12">
                            <div class="thumbnail">
                                {% if obj.GPU_image %}
                                    <img src='{{ obj.GPU_image.url }}' class='img-responsive'>
                                {% endif %}
                                <div class="caption">
                                    <h3>{{ obj.GPU_model }}</h3>
                                    <p>{{ obj.GPU_content|linebreaks }}</p>
                                <fieldset disabled>
                                    <button type="" class="btn btn-primary">P {{ obj.GPU_cost }}</button>
                                </fieldset>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% endfor %}
                </div>
                <!-- /.row -->

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src='{% static "js/jquery.js"%}'></script>

    <!-- Bootstrap Core JavaScript -->
    <script src='{% static "js/bootstrap.min.js"%}'></script>

</body>

</html>

src/templates/moth1150.html
{%load staticfiles%}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PC BUILDER</title>

    <!-- Bootstrap Core CSS -->
    <link href='{% static "css/bootstrap.min.css"%}' rel="stylesheet">

    <!-- Custom CSS -->
    <link href='{% static "css/sb-admin.css"%}' rel="stylesheet">

    <!-- Custom Fonts -->
    <link href='{% static "font-awesome/css/font-awesome.min.css"%}' rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href='{% url "posts:main" %}'>PC BUILDER</a>
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li class="active">
                        <a href='{% url "posts:home" %}'><i class="fa fa-fw fa-wrench"></i> BUILD PC</a>
                    </li>
                    <li>
                        <a><i class="fa fa-fw fa-desktop"></i> COMPONENTS</a>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo_p"><i class="glyphicon glyphicon-triangle-right"></i> Intel Processor <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo_p" class="collapse">
                            <li>
                                <a href='{% url "posts:proc1150" %}'>LGA 1150</a>
                            </li>
                            <li>
                                <a href='{% url "posts:proc1151" %}'>LGA 1151</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo_mb"><i class="glyphicon glyphicon-triangle-right"></i> Intel Motherboard <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo_mb" class="collapse">
                            <li>
                                <a href='{% url "posts:moth1150" %}'>LGA 1150</a>
                            </li>
                            <li>
                                <a href='{% url "posts:moth1151" %}'>LGA 1151</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo_me"><i class="glyphicon glyphicon-triangle-right"></i> Memory <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo_me" class="collapse">
                            <li>
                                <a href='{% url "posts:ddr4" %}'>DDR4</a>
                            </li>
                            <li>
                                <a href='{% url "posts:ddr3" %}'>DDR3</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href='{% url "posts:store" %}'><i class="glyphicon glyphicon-triangle-right"></i> Storage </a>
                    </li>
                    <li>
                        <a href='{% url "posts:gpu" %}'><i class="glyphicon glyphicon-triangle-right"></i>Graphics Card</a>
                    </li>
                    <li>
                        <a href='{% url "posts:psu" %}'><i class="glyphicon glyphicon-triangle-right"></i>Power Supply</a>
                    </li>
                    <li>
                        <a href='{% url "posts:case" %}'><i class="glyphicon glyphicon-triangle-right"></i>Casing</a>
                    </li>
                    <li>
                        <a href='{% url "posts:contact" %}'><i class="glyphicon glyphicon-earphone"></i>CONTACT US</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            LGA 1150 Motherboard
                        </h1>
                    </div>
                    {% for obj in items %}

                    <div class="row">
                        <div class="col-lg-12">
                            <div class="thumbnail">
                                {% if obj.mobo_image %}
                                    <img src='{{ obj.mobo_image.url }}' class='img-responsive'>
                                {% endif %}
                                <div class="caption">
                                    <h3>{{ obj.mobo_model }}</h3>
                                    <p>{{ obj.mobo_content|linebreaks }}</p>
                                <fieldset disabled>
                                    <button type="" class="btn btn-primary">P {{ obj.mobo_cost }}</button>
                                </fieldset>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% endfor %}
                </div>
                <!-- /.row -->

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src='{% static "js/jquery.js"%}'></script>

    <!-- Bootstrap Core JavaScript -->
    <script src='{% static "js/bootstrap.min.js"%}'></script>

</body>

</html>

src/templates/practice.html
<h1>Contact</h1>
<form role="form" action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>

src/templates/sendEmail.html
def post_practice(request):
    form_class = PracticeForm
    if request.method == 'POST':
    	form = form_class(data=request.POST)
    	if form.is_valid():
    		contact_name = request.POST.get('contact_name','')
    		contact_email = request.POST.get('contact_email','')
    		form_content = request.POST.get('content','')

    		template = get_template('contact_template.txt')
    		context = Context({
    			'contact_name': contact_name,
    			'contact_email': contact_email,
    			'form_content': form_content,
    			})
    		content = template.render(context)

    		email = EmailMessage(
    			"New Contact Form Submission",
    			content,
    			"Your Website" + '',
    			['youremail@gmail.com'],
    			headers = {'Reply-To': contact_email}
    			)
    		email.send()
    
    return render(request, 'practice.html', {
        'form': form_class,
    })

def post_contact(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            messages.success(request, "Thank You. Your message has been sent")
    return render(request, "Contact.html", {'form':form})